// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller.js"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import MapController from "./map_controller.js"
application.register("map", MapController)

import ScannerController from "./scanner_controller.js"
application.register("scanner", ScannerController)

import ReadMoreController from "./read_more_controller.js"
application.register("read-more", ReadMoreController)

import UpdateAreaController from "./update_area_controller.js"
application.register("update-area", UpdateAreaController)
