meta_product_name: "Matchbooks"
meta_title: "Matchbooks - Find books in your area"
meta_description: "Matchbooks is a book sharing platform from Berlin. Find books in your area and meet like-minded people"
meta_image: "cover.png" # should exist in `app/assets/images/`
